const mongoose = require("mongoose");

//We will create an schema

const paymentSchema = new mongoose.Schema({
    //first thing is order id generated by the Rajorpay.
    //iska use hm payment ko dhundane aur update karne k liye karte hai
    razorpay_order_id :{
        type:String,
        required:true,
        unique:true,
    },
    //Payment id : after successfull payment this id is generated.

    razorpay_payment_id:{
        type:String,
    },

    //The signature : sent by rajorpay for authentication . 
     // this is also uysed in 'verifypaymentstep'.
     razorpay_signature:{
        type:String,
     },

     //The amount (kitna paisa hai) 500 rupaye amount == 500
     amount:{
        type:Number,
        required:true,
     },
     //konsi cuyrrency used hai 
     currency:{
        type:String,
        required:true,
     },

     //Status
     //Three types of status are there
     // " created " --> jab order create hota .
     // " paid "--> jab payment successfully verify ho jati hai .
     //" failed " --> jab payment failed ho jati hai .
     status:{
        type:String,
        enum: ['created', 'paid', 'failed'],
        default:'created',
        required: true,
     },
     //The reciept Id you provided when you creating the order.
     receipt:{
        type:String,
     },
     //Linking to the user who made the payemnet (for authentication)
     //aasuming we have User model
     user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        // required:true, //as we have user auth.

     },
    //Automatically adds createdAt and updated at fields.
    timestamps:true
});
//
module.exports = mongoose.model("Payment",paymentSchema);
